name: Deploy Docs
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build and deploy documentation from"
        required: true
        default: "main"
        
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Pull docs repository
        uses: actions/checkout@v4
        with:
          repository: moonbeam-foundation/moonbeam-docs
          path: moonbeam-docs
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential
      - name: Install pip requirements
        run: |
          # upgrade pip
          python -m pip install --upgrade pip setuptools 'cython<3.0.0' wheel
          # install dependencies quietly
          python -m pip install -r requirements.txt
      - name: Update image paths in Markdown files
        run: |
          # Replace old image paths with new paths in Markdown files
          find moonbeam-docs -type f -name "*.md" -exec sed -i -e 's|](/|](/moonbeam-mkdocs/|g' -e 's|href="/|href="/moonbeam-mkdocs/|g' {} \;
      - name: Replace `/assets` with `assets`
        run: |
          find . -type f -exec sed -i 's|/assets|assets|g' {} +
      - name: Deploy Docs
        run: mkdocs gh-deploy --force --clean --site-dir ./site
