#!/bin/bash
LOGPATH=/var/log/s3_moonbeam_docs_sync.log
DOCPATH=/var/www/moonbeam-docs-cn-stage
STATICPATH=/var/www/moonbeam-docs-static/cn
# check for repo changes
cd $DOCPATH/moonbeam-docs-cn
if /usr/bin/git checkout master &&
    /usr/bin/git fetch origin master &&
    [ `/usr/bin/git rev-list HEAD...origin/master --count` != 0 ]
then
    echo . >>$LOGPATH
    echo +++ $(date +%F' '%H:%M:%S) - Pulling Changes from Github... >>$LOGPATH
    # pull changes
    /usr/bin/git merge origin/master &>>$LOGPATH

    # build mkdoc
    echo 'docs updated, building site' >>$LOGPATH
    cd ..
    /usr/local/bin/mkdocs build --clean &>>$LOGPATH

    # fix relative links to include language subdir
    find $STATICPATH -type f -name index.html -exec sed -i "s|href=\"\/|href=\"\/cn\/|g" '{}' \;

    echo +++ Finished at $(date +%F' '%H:%M:%S) +++++++++++++++++++ >>$LOGPATH
fi
# reset file and directory permissions
chown root:users -R $DOCPATH
find $DOCPATH/ -type d -exec chmod 775 {} \;
find $DOCPATH/ -type f -exec chmod 664 {} \;
chmod 774 $DOCPATH/git_sync
